/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_filltriangle_GL2JNILib */

#ifndef _Included_com_example_filltriangle_GL2JNILib
#define _Included_com_example_filltriangle_GL2JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_filltriangle_GL2JNILib
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_zkzszd_opengl_GL2JNILib_init
  (JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL Java_zkzszd_opengl_GL2JNILib_putCameraData(JNIEnv* env,
            jclass clazz,jint jwidth, jint jheight, jbyteArray jyuv_data);

/*
 * Class:     com_example_filltriangle_GL2JNILib
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zkzszd_opengl_GL2JNILib_step
    (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
